%---------------------------------------------------------------------------------------------------
% template document
\documentclass[12pt, a4paper, twoside, openright, openany]{book}
\input{\Sexpr{REP$style}}
\input{\Sexpr{REP$style_math}}

%---------------------------------------------------------------------------------------------------
%\SetWatermarkText{\Sexpr{REP$watermark}}
\SetWatermarkText{}
\SetWatermarkScale{0.40}
\SetWatermarkColor[gray]{0.7}


% Bibliografía -------------------------------------------------------------------------------------
\addbibresource{\Sexpr{REP$bib_lib}}
\addbibresource{\Sexpr{REP$bib_art}}
\addbibresource{\Sexpr{REP$bib_ley}}

%---------------------------------------------------------------------------------------------------
% Inicio del documento
\begin{document}

%---------------------------------------------------------------------------------------------------
%\frontmatter
% Contenidos
<<cap01, child='01_cobertura.Rnw'>>=
@

<<cap02, child='02_contenido.Rnw'>>=
@

%---------------------------------------------------------------------------------------------------
% Cuerpo del estudio
\mainmatter

<<cap03, child='03_resumen_ejecutivo.Rnw'>>=
@

<<cap04, child='04_antecedentes.Rnw'>>=
@
  
<<cap05, child='05_base_legal.Rnw'>>=
@
 
<<cap06, child='06_analisis_contexto.Rnw'>>=
@
  
<<cap07, child='07_demografia.Rnw'>>=
@

<<cap08, child='08_resultados.Rnw'>>=
@

<<cap09, child='09_conclusion.Rnw'>>=
@

%---------------------------------------------------------------------------------------------------
% Apéndices
\appendix
%\appendixpage

%---------------------------------------------------------------------------------------------------
% Acrónimos

%---------------------------------------------------------------------------------------------------
%\backmatter

% Bibliografía
\printbibliography
\addcontentsline{toc}{chapter}{Bibliografía}

\end{document}
